// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    SConverter: typeof import('./../components/SConverter.vue')['default']
    SConverterInput: typeof import('./../components/SConverterInput.vue')['default']
  }
}

export { }
